USE HowKteam

GO

--LEFT JOIN 

SELECT * FROM dbo.BOMON JOIN dbo.GIAOVIEN
ON GIAOVIEN.MABM = BOMON.MABM

--BẢNG BÊN PHẢI NHẬP VÀO BẢNG BÊN TRÁI 
--RECORD NÀO BẢNG PHẢI KHÔNG CÓ THÌ ĐỂ NULL
--RECORD NÀO BẢNG TRÁI KHÔNG CÓ THÌ KHÔNG ĐIỀN VÀO 

SELECT *FROM dbo.BOMON LEFT JOIN dbo.GIAOVIEN
ON GIAOVIEN.MABM = BOMON.MABM

--RINGHT JOIN 

SELECT *FROM dbo.BOMON RIGHT JOIN dbo.GIAOVIEN
ON GIAOVIEN.MABM = BOMON.MABM